import BlogItem, { BlogProps } from "@/components/BlogItem";
import PageTitle from "@/components/PageTitle";
import ProductItem, { ProductProps } from "@/components/ProductItem";
import type { NextPage } from "next";
import Head from "next/head";

async function fetchBlogData(query: string): Promise<BlogProps[]> {
  const blogRes = await fetch(`http://localhost:5001/blogs?&q=${query}`);
  const blogData = blogRes.json();

  return blogData;
}
async function fetchProductData(query: string): Promise<ProductProps[]> {
  const productRes = await fetch(`http://localhost:5001/products?&q=${query}`);
  const productData = productRes.json();

  return productData;
}

export default async function Search({
  searchParams,
}: {
  searchParams: { q: string };
}) {
  const blogData = await fetchBlogData(searchParams.q);
  const productData = await fetchProductData(searchParams.q);
  return (
    <>
      <Head>
        <title>Store - Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={"Search"} />

      <div className="bg0 m-t-23 p-b-140 mt-5">
        <div className="container">
          {/* blogs  */}
          <>
            <h2 className="mb-5">Blogs</h2>
            <div className="row isotope-grid">
              {/* blog skeleton - search result */}
              <div className="col-4">
                <BlogItem blogProps={blogData} />
              </div>
              {/* !! */}
            </div>
          </>

          {/* products */}
          <>
            <h2 className="mb-5">Products</h2>
            <div className="row isotope-grid">
              {/* product skeleton */}
              <ProductItem productItems={productData} />
              {/* !! */}
            </div>
          </>
        </div>
      </div>
    </>
  );
}
